[[redirects]]
  from = "api/*"
  to = "https://rv.5giotlead.com:8080/api/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  # headers = {X-From = "Netlify"}

[[redirects]]
  from = "smartrv/*"
  to = "https://rv.5giotlead.com:8080/smartrv/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
 
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
